### PR TITLE
Bug Fixed reduce the gap between date and publish text #329

### LINKED ISSUE #329: [Bug]-Blog Detail Page-Incorrect Gap in Blog Detail Page Heading Date Compared to Figma Design
Description:
On the blog detail page, the gap between the publication date and the heading doesn't match the design provided in Figma. This inconsistency affects the visual alignment of the content.

Steps to Reproduce:

1. Navigate to a blog detail page.
2. Locate the publication date and the heading of the blog post.
3. Observe the gap between the publication date and the heading.
4. Compare this gap with the design presented in Figma.
5. Note any discrepancies in the alignment and spacing.

Expected Result:
The gap between the publication date and the heading on the blog detail page should match the design provided in Figma, ensuring consistent spacing and alignment.

Actual Result:
The gap between the publication date and the heading on the blog detail page does not match the design from Figma, resulting in an inconsistent layout.

Image

Image

### PR DESCRIPTION
**Pull request by Sanjeewa001**
big fixed #329

### CODE REVIEW

**Comment by Sanjeewa001** [comment]
Bug fixed - #330

**Comment by Sanjeewa001** [comment]
Bug #327 Fixed

**Comment by Sanjeewa001** [comment]
#326 Fixed limitation in some device in as there breakpoints

**Comment by Sanjeewa001** [comment]
#326 Fixed limitation in some device in as there breakpoints

**Review by iamarasekera — APPROVED** [review]

**Pull request merged**
